# Generated by Django 3.2.4 on 2023-06-20 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Metropolitana', 'Metropolitana'), ('Arica y parinacota', 'Arica y parinacota'), ('Tarapaca', 'Tarapaca'), ('Atacama', 'Atacama'), ('Coquimbo', 'Coquimbo'), ('Valparaiso', 'Valparaiso'), ("Libertador Bernardo O'Higgins", "Libertador Bernardo O'Higgins"), ('Maule', 'Maule'), ('BioBio', 'BioBio'), ('Araucania', 'Araucania'), ('Los rios', 'Los rios'), ('Los lagos', 'Los lagos'), ('Aysen', 'Aysen'), ('Magallanes y de la Antártica Chilena', 'Magallanes y de la Antártica Chilena')], max_length=200)),
                ('nivelEducacional', models.CharField(choices=[('Doctorado', 'Doctorado'), ('Magister', 'Magister'), ('Profesional', 'Profesional')], max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
