# Generated by Django 3.2.4 on 2023-07-09 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_remove_cliente_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='cliente',
        ),
        migrations.AddField(
            model_name='carrito',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrito',
            name='total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
