# Generated by Django 3.2.4 on 2023-07-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230709_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nro_tarjeta', models.IntegerField()),
                ('fecha', models.DateField()),
                ('ccv', models.IntegerField()),
                ('cant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('nro_depto', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=100)),
                ('cod_postal', models.IntegerField()),
                ('tarjeta_nom', models.CharField(max_length=100)),
                ('nro_tarjeta', models.IntegerField()),
                ('ccv', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
